/* ==========================================================================
   APMS.ai — tools/deploy-list.js
   node tools/deploy-list.js

   Rewrites the file list inside DEPLOY.txt from what is actually in the repo.

   This exists because DEPLOY.txt has now drifted twice. The first time it left
   five stylesheets off and shipped a site with broken styling. The second time
   was worse: it listed every source file under css/ but none of the built
   bundles under dist/css/, which are the only stylesheets the pages link at
   all - so following it would have uploaded a complete set of CSS that no page
   references and shipped an entirely unstyled site. It also lost
   assets/fonts/, js/core/gsap-late.js and llms.txt along the way.

   A generator already existed for this - docs/gen-deploy-manifest.py - and the
   drift was not caused by nobody running it. It was written before the CSS was
   bundled, and it selected files with a whitelist: `top in ('css','js','assets')
   or p.endswith(('.html','.php'))`. dist/ is not in that list, so the bundles
   could never appear in its output however often it ran, and llms.txt could
   not either. Its referenced-asset check had the same blind spot - the regex
   matched only `(?:css|js|assets)/`, so the dist/ links it was failing to list
   were invisible to it as well.

   A whitelist of folder names has to be updated every time the layout changes,
   and it fails silently when it is not. This derives the list from the set of
   committed files instead, so a new folder is included the moment a file in it
   is committed, and the reference check below looks at every local href and
   src rather than a chosen subset.

   The list is derived from `git ls-files`, so a file that is committed is a
   file that gets uploaded, and there is no second place to remember. Only the
   development-only paths below are held back.

   RE-RUN THIS whenever files are added or removed, and always after
   `node tools/bundle.js` changes a bundle's hash - the hashed filename is in
   this list, so a stale list names a bundle that is no longer on disk.
   ========================================================================== */
"use strict";

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
const DEPLOY = path.join(ROOT, "DEPLOY.txt");

/* Committed, but never served. Everything else in the repo goes up.
   Erring towards uploading a file that is not strictly needed is harmless;
   erring the other way is how the site ends up without its stylesheet. */
const DEV_ONLY = [
  ".gitignore",
  ".gitattributes",
  "DEPLOY.txt",
  "docs/",      /* notes and setup guides */
  "tools/",     /* the bundler and this script */
];

/* Configuration for GitHub itself, not part of the site in any sense. Listing
   it under "never upload" would be noise - nobody deploying a website is going
   to wonder whether CODEOWNERS belongs in public_html - so it is left out of
   the file entirely rather than held back with an explanation. Without this it
   would land in the *upload* list, because it is neither dev-only nor
   ignored. */
const NOT_SITE = [".github/"];

function isDevOnly(f) {
  return DEV_ONLY.some(function (p) {
    return p.endsWith("/") ? f.startsWith(p) : f === p;
  });
}

function isNotSite(f) {
  return NOT_SITE.some(function (p) { return f.startsWith(p); });
}

const tracked = execSync("git ls-files", { cwd: ROOT, encoding: "utf8" })
  .split("\n")
  .map(function (s) { return s.trim(); })
  .filter(Boolean);

const site = tracked.filter(function (f) { return !isNotSite(f); });
const upload = site.filter(function (f) { return !isDevOnly(f); }).sort();
const held = site.filter(isDevOnly).sort();

/* Sanity check, because the whole point of this file is that a wrong list is
   worse than no list: every local href/src in every page must be in `upload`.
   If a page links something we are not uploading, say so and fail loudly. */
const set = new Set(upload);
const missing = [];
for (const page of upload.filter(function (f) { return f.endsWith(".html"); })) {
  const html = fs.readFileSync(path.join(ROOT, page), "utf8");
  const re = /(?:href|src)="(?!https?:|\/\/|#|mailto:|tel:|data:)([^"]+)"/g;
  let m;
  while ((m = re.exec(html))) {
    const ref = m[1].split("?")[0].split("#")[0];
    if (!ref || ref.endsWith("/")) continue;
    if (!set.has(ref) && fs.existsSync(path.join(ROOT, ref))) missing.push(ref + "  (linked from " + page + ")");
  }
}

const head = fs.readFileSync(DEPLOY, "utf8").split(/^-{40}$/m)[0].trimEnd();

const body =
  head + "\n\n" +
  "----------------------------------------\n" +
  "  " + upload.length + " files\n" +
  "  Generated by tools/deploy-list.js - do not hand-edit below this line.\n" +
  "----------------------------------------\n\n" +
  upload.map(function (f) { return "  " + f; }).join("\n") + "\n\n" +
  "Never upload these:\n\n" +
  held.map(function (f) { return "  " + f; }).join("\n") + "\n" +
  "  config.php            (not in the repository at all: it holds the\n" +
  "                         database and SMTP passwords. Its shape is\n" +
  "                         documented in the header of submit.php.)\n\n" +
  "Run once on the server, in hPanel > Databases > phpMyAdmin > SQL:\n" +
  "  the CREATE TABLE in the header of submit.php, which makes the\n" +
  "  enquiries table.\n";

fs.writeFileSync(DEPLOY, body);

console.log("DEPLOY.txt rewritten: " + upload.length + " files to upload, " + held.length + " held back");
if (missing.length) {
  console.error("\nERROR: pages link files that are not in the upload list:");
  missing.forEach(function (m) { console.error("  " + m); });
  process.exit(1);
}
console.log("checked: every local href/src in every page is in the list");
